using System.Collections.Generic;
using System.Threading.Tasks;
using Game.Dialog;
using Sfs2X.Entities.Data;

namespace App.BomberLand {
    public interface IGeneralServerBridge : IServerManagerDelegate {
        Task<IHeroPower[]> GetHeroPower();
        Task<ISyncHeroResponse> SyncHero(bool notifyNewIds, bool isBuyHero = false);
        Task<ISyncHeroResponse> FetchMoreHeroes(int offset, int limit);
        ISyncHeroResponse SyncHero(ISFSObject data);
        Task<ISyncHouseResponse> SyncHouse();
        Task<ISyncHouseResponse> FetchMoreHouses(int offset, int limit);
        ISyncHouseResponse SyncHouse(ISFSObject data);
        Task<IChestReward> GetChestReward();
        Task<bool> ReactiveHouse(int houseId);
        Task<IApproveClaimResponse> ApproveClaim(int code);
        Task<float> ConfirmApproveClaimSuccess(int code);
        Task<IChestReward> SyncDeposited();
        IChestReward SyncDeposited(ISFSObject data);
        Task<IAutoMinePackages> GetAutoMinePrice();
        Task<IChestReward> BuyAutoMine(string packageName, BlockRewardType blockRewardType);
        Task<IRockPackage> BuyRockPack(string packageName, BlockRewardType rewardType);
        Task<bool> StartAutoMine();
        Task RepairShield(HeroId heroId, BlockRewardType rewardType);
        Task<bool> ChangeMiningToken(string type, double bcoinInWallet);
        Task<IAirDropResponse> GetAirDrop();
        Task<IAirDropClaimResponse> ClaimAirDrop(string nftCode);
        Task<bool> ConfirmClaimAirDrop(string nftCode);
        Task<bool> UserRename(string newName, BlockRewardType type);
        Task<bool> LinkUser(UserAccount account);
        Task<double> Stake(float bcoin, BlockRewardType type, bool stakeAll);
        Task<IStakeResult> GetStakeInfo();
        Task<IStakeResult> WithdrawStake();
        Task<IVipStakeResponse> UserStakeVip();
        Task<IVipStakeResponse> UserClaimStakeVip(VipRewardType type);
        Task<ILuckyRewardsResponse> StartLuckWheel(int amount);
        Task<IDailyMissionListResponse> GetDailyMissions();
        Task<bool> ClaimLuckyTicketDailyMission(string missionCode);
        Task<IEmailResponse> GetEmail();
        Task<bool> RegisterEmail(string email);
        Task<bool> VerifyEmail(int verifyCode);
        Task<IChestReward> BuyTicket(BlockRewardType currency, int amount, BlockRewardType ticketType);
        Task BuyLuckyTicket(int amount);
        Task<IServerConfigResponse> GetConfig();
        Task<float> PreviewToken(float balance, NetworkType networkType, int tokenType);
        Task<float> SwapToken(float balance, NetworkType networkType, int tokenType);
        Task<int> GetSwapTokenConfig();
        void KeepJoiningPvPQueue();
        Task<IMinStakeHeroManager> GetMinStakeHero();
        Task<IRepairShieldConfig> GetRepairShieldConfig();
        Task GetRockPackConfig();
        Task GetRentHousePackageConfig();
        Task<ITreasureHuntConfigResponse> GetTreasureHuntDataConfig();
        void SendMessageSlack(string title, SFSObject info);
        Task<IBurnHeroConfig> GetBurnHeroConfig();
        Task BurnHero();
        Task<IUpgradeShieldConfig> GetUpgradeShieldConfig();
        Task<IUpgradeShieldResponse> UpgradeLevelShield(HeroId heroId);
        void UpdateUserReward(ISFSObject data);
        Task<IBuyHeroServerResponse> BuyHeroServer(int quantity, int rewardType, bool isBuyHero = false);
        Task<IHouseDetails> BuyHouseServer(int rarity, int rewardType);
        Task<IOfflineReward> GetOfflineReward();
        IReferralData InitReferralData(ISFSObject data);
        Task<IClubInfo> GetClubInfo();
        Task<IClubInfo> GetClubInfo(long clubId);
        Task<IClubRank[]> GetAllClub();
        Task<IClubInfo> JoinClub(long clubId);
        Task<IClubInfo> JoinAnotherClub(string clubName);
        Task<IClubInfo> CreateClub(string clubName);
        Task LeaveClub();
        Task<IClubBidPrice[]> GetBidPrice(long clubId);
        Task<IClubRank[]> GetTopBidClub();
        Task<IClubBidPrice[]> BoostClub(long clubId, int packageId);
        Task<string> GetInvoiceSol(double amount, DepositType depositType);
        Task<ISyncHeroResponse> AddHeroForAirdropUser();
        Task<IFusionTonHeroResponse> FusionHeroServer(int target, int[] heroList);
        Task<IFusionTonHeroResponse> MultiFusionHeroServer(int target, int[] heroList);
        Task GetHeroOldSeason();
        Task<long> RentHouse(int houseId, int numDays);
        Task GetOnBoardingConfig();
        Task UpdateUserOnBoarding(int step, int claimed = 0);
        void SendClientLog(List<ClientLogEntry> logData);
        Task<string> GetInvoice(double amount, DepositType depositType);
    }
}